language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6

before_script: composer install -n

before_install:
    - sudo apt-get update > /dev/null

install:
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-intl xvfb firefox > /dev/null
    - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
    - sudo /etc/init.d/apache2 restart

before_script:
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - composer self-update
    - composer install --prefer-source --no-interaction

    - npm install -g bower
    - bower install

    - curl -L https://github.com/yui/yuicompressor/releases/download/v2.4.8/yuicompressor-2.4.8.jar > bin/yuicompressor.jar

    - app/console doctrine:database:create
    - app/console doctrine:schema:create
    - app/console assets:install
    - app/console assetic:dump

    - chmod -R 777 app/cache app/logs
    - app/console --env=test cache:warmup
    - chmod -R 777 app/cache app/logs

    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99
    - sleep 5
    - curl http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar > selenium.jar
    - java -jar selenium.jar > /dev/null &
    - sleep 15

script:
    - bin/phpunit -c app
    - bin/behat